export {default as HeroSection} from "../containers/HeroSection/HeroSection"
export {default as Body} from "../containers/Body/Body"
export {default as Body2} from "../containers/Body2/Body2"
export {default as Reviews} from "../containers/Reviews/Reviews.js"
export {default as Images} from "../containers/Images/Images.js"
export {default as Footer} from "../containers/Footer/Footer.js"
